// frontend/pages/dataChugchilan.js
export const respuestas = [
  { respuesta: "Chugchilán está en Cotopaxi, cantón Sigchos, a 3200 m.s.n.m." },
  { respuesta: "Se encuentra cerca de la Laguna de Quilotoa, parte del Quilotoa Loop." },
  { respuesta: "El clima es frío y húmedo, ideal para senderismo y trekking." },
  { respuesta: "La población es indígena Kichwa y mestiza, con cultura viva." },
  { respuesta: "Prueba la gallina criolla, mote pillo y quesillo artesanal." },
  { respuesta: "Los hostales locales son manejados por familias campesinas." },
  { respuesta: "Puedes hacer trekking hacia Isinliví, Sigchos y la Laguna de Quilotoa." },
  { respuesta: "La ruta es famosa entre mochileros que recorren la Sierra Centro." },
  { respuesta: "La economía combina turismo comunitario, agricultura y artesanías." },
  { respuesta: "Visita los miradores para vistas panorámicas del páramo andino." },
  { respuesta: "Septiembre es el mes de fiestas patronales con música y danzas." },
  { respuesta: "Puedes encontrar tejidos y cerámicas hechas a mano por artesanos." },
  { respuesta: "Muchos senderos se pueden recorrer a caballo o en bicicleta de montaña." },
  { respuesta: "Rebaños de ovejas, llamas y alpacas son parte del paisaje local." },
  { respuesta: "Las noches son frías, lleva ropa térmica y abrigo." },
  { respuesta: "El cielo estrellado es inolvidable en noches despejadas." },
  { respuesta: "Los niños locales suelen presentar danzas folklóricas en festividades." },
  { respuesta: "Algunos hostales cultivan su comida en huertos propios." },
  { respuesta: "Reserva hospedaje con antelación en temporada alta (junio-septiembre)." },
  { respuesta: "Los caminos de tierra se vuelven resbaladizos en época de lluvias." },
  { respuesta: "Puedes adquirir quesos frescos directamente de productores locales." },
  { respuesta: "Turismo comunitario permite interactuar con familias campesinas." },
  { respuesta: "Lleva efectivo, hay pocos cajeros automáticos en la zona." },
  { respuesta: "Es ideal para fotografía de paisajes, flora y aves andinas." },
  { respuesta: "Participa en talleres de quesería o tejido organizados por locales." },
  { respuesta: "Chugchilán es perfecto para desconectarse de la tecnología." },
  { respuesta: "Hay transporte público desde Latacunga y Sigchos, revisa horarios." },
  { respuesta: "Las casas conservan arquitectura rústica con piedra y madera." },
  { respuesta: "Los artesanos usan lana de oveja para tejer bufandas y tapices." },
  { respuesta: "En días despejados puedes ver volcanes como los Illinizas." },
  { respuesta: "Los locales suelen compartir leyendas sobre lagunas y montañas." },
  { respuesta: "La iglesia del pueblo es sencilla pero significativa para la comunidad." },
  { respuesta: "Puedes encontrar productos orgánicos en mercados locales." },
  { respuesta: "Si manejas, revisa frenos y gasolina antes de subir a la parroquia." },
  { respuesta: "Algunas familias ofrecen guianza para rutas seguras de trekking." },
  { respuesta: "En la noche, fogatas y tertulias en patios de hostales son comunes." },
  { respuesta: "Los turistas valoran mucho la calidez y amabilidad de la gente." },
  { respuesta: "En días de fiesta hay corridas de toros y ferias artesanales." },
  { respuesta: "Hay clínicas básicas, para emergencias mayores acude a Latacunga." },
  { respuesta: "La conectividad a internet es limitada: ideal para relajarse sin notificaciones." },
  { respuesta: "Puedes comprar choclo con queso y dulces andinos en ferias locales." },
  { respuesta: "La parroquia promueve un turismo responsable y sostenible." },
  { respuesta: "Las montañas cercanas ofrecen flora única y paisajes de ensueño." },
  { respuesta: "La altitud y clima favorecen la agricultura de papa y maíz." },
  { respuesta: "En algunos senderos puedes observar cóndores y aves rapaces." },
  { respuesta: "Los domingos hay mercados campesinos con venta de productos frescos." },
  { respuesta: "Chugchilán es punto clave para aventureros que recorren la Sierra central." },
  { respuesta: "La caminata Quilotoa - Chugchilán es una de las más recomendadas." },
  { respuesta: "No olvides bloqueador solar y gorra: el sol es fuerte a gran altura." },
  { respuesta: "La hospitalidad campesina es uno de los mayores tesoros de Chugchilán." }
];
